application: papt
version: 1
runtime: python27
api_version: 1
threadsafe: yes
skip_files:
- .*node_modules/.*
- .*pyc$
- .*\.sw[op]$

handlers:
- url: /$
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"

- url: /user/.*
  script: user_actions.app

- url: /test/.*
  script: test_actions.app

- url: /
  static_dir: static/
  expiration: "15m"
  application_readable: true

- url: /sound
  static_dir: static/sound
  expiration: "7d"


- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
